# Based on https://github.com/changesets/action#with-publishing
name: Publish

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Setup publish token
        run: cp publish.npmrc .npmrc

      - name: Run Lerna publish
        run: yarn lerna publish from-package --yes
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
